<?xml version="1.0" encoding="utf-8"?><Database Name="dental" Class="MaindbModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=constantine;Initial Catalog=dental;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dentalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Patient" Member="Patients">
    <Type Name="Patient">
      <Column Name="PatientNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IDNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BloodType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HaveAdditionalInfo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AdditionalInfo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MarialStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
      <Association Name="Patient_Appointment" Member="Appointments" ThisKey="PatientNo" OtherKey="PatientNo" Type="Appointment" />
      <Association Name="Patient_PatientFile" Member="PatientFiles" ThisKey="PatientNo" OtherKey="PatientNo" Type="PatientFile" />
    </Type>
  </Table>
  <Table Name="dbo.Appointment" Member="Appointments">
    <Type Name="Appointment">
      <Column Name="AppNo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PatientNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DrNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Appointment_PatientFile" Member="PatientFiles" ThisKey="AppNo" OtherKey="AppNo" Type="PatientFile" />
      <Association Name="Patient_Appointment" Member="Patient" ThisKey="PatientNo" OtherKey="PatientNo" Type="Patient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Doctor" Member="Doctors">
    <Type Name="Doctor">
      <Column Name="DrNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PhoneNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Office" Member="Offices">
    <Type Name="Office">
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkingHours" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Holidays" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PatientFile" Member="PatientFiles">
    <Type Name="PatientFile">
      <Column Name="AppNo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PatientNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Prescription" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TreatmentDetails" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Appointment_PatientFile" Member="Appointment" ThisKey="AppNo" OtherKey="AppNo" Type="Appointment" IsForeignKey="true" />
      <Association Name="Patient_PatientFile" Member="Patient" ThisKey="PatientNo" OtherKey="PatientNo" Type="Patient" IsForeignKey="true" />
    </Type>
  </Table>
</Database>